TakeREST/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TakeREST.Models
{
    public class Photo
    {
        public int AblumID { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string ThumbnailUrl { get; set; }
    }
}

TakeREST/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TakeREST.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TakeREST/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TakeREST.Models;

namespace TakeREST.Controllers
{
    public class PhotosController : Controller
    {
        public static string BaseUrl = "https://jsonplaceholder.typicode.com";
        // GET: Photos
        public async Task<ActionResult> Index()
        {
            var client = new HttpClient();
            var response = await client.GetAsync(BaseUrl + "/photos");
            if (response.IsSuccessStatusCode)
            {
                var photos = await response.Content.ReadAsAsync<IEnumerable<Photo>>();
                return View(photos);
            }
            return new HttpStatusCodeResult(response.StatusCode);
        }

        // GET: Photos/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var client = new HttpClient();
            var response = await client.GetAsync(BaseUrl + "/photos/" + id);
            if (response.IsSuccessStatusCode)
            {
                var photo = await response.Content.ReadAsAsync<Photo>();
                return View(photo);
            }
            return new HttpStatusCodeResult(response.StatusCode);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        [HttpPost]
        public async Task<ActionResult> Create(Photo photo)
        {
            var client = new HttpClient();
            var response = await client.PostAsJsonAsync(BaseUrl + "/photos", photo);
            if (response.IsSuccessStatusCode)
            {
                var photoResult = response.Content.ReadAsAsync<Photo>();
                return RedirectToAction("Details", new { id = photoResult.Id });
            }
            return new HttpStatusCodeResult(response.StatusCode);
        }

        // GET: Photos/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var result = await Details(id);
            var viewResult = result as ViewResult;
            if (viewResult != null)
            {
                var photo = viewResult.Model as Photo;
                return View();
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
        }

        // POST: Photos/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Photo photo)
        {
            var client = new HttpClient();
            var response = await client.PostAsJsonAsync(BaseUrl + "/photos/" + photo.Id, photo);
            if (response.IsSuccessStatusCode)
            {
                var photoResult = response.Content.ReadAsAsync<Photo>();
                return RedirectToAction("Details", new { id = photoResult.Id });
            }
            return new HttpStatusCodeResult(response.StatusCode);

        }

        // GET: Photos/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var result = await Details(id);
            var viewResult = result as ViewResult;
            if (viewResult != null)
            {
                var photo = viewResult.Model as Photo;
                return View(photo);
            }
            return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
        }

        // POST: Photos/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Photo photo)
        {
            var client = new HttpClient();
            var response = await client.DeleteAsync(BaseUrl + "/photos/" + photo.Id);
            if (response.IsSuccessStatusCode)
                return RedirectToAction("Index");
            else return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError);
        }
    }
}

TakeREST/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Take REST</h1>
    <p class="lead">Take REST is a demo application created in ASP.NET framework to show how to consume REST Service which are platform agnostic and can be called from anywhere e.g. Java, .NET, jQuery, Angular etc.</p>
    <p><a href='@Url.Action("Index", "Photos")' class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

TakeREST/Views/Photos/Create.cshtml
@model TakeREST.Models.Photo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AblumID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AblumID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AblumID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThumbnailUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThumbnailUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThumbnailUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TakeREST/Views/Photos/Delete.cshtml
@model TakeREST.Models.Photo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <div class="container">
        <div class="col-xs-6">

            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.AblumID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AblumID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Url)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Url)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ThumbnailUrl)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ThumbnailUrl)
                </dd>

            </dl>
        </div>
        <div class="col-xs-6">
            <img  src="@Model.ThumbnailUrl" alt="Photo"/>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TakeREST/Views/Photos/Details.cshtml
@model TakeREST.Models.Photo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <div class="container">
        <div class="col-sm-6">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.AblumID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AblumID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Url)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Url)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ThumbnailUrl)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ThumbnailUrl)
                </dd>

            </dl>
        </div>
        <div class="col-sm-6">
            <img src="@Model.ThumbnailUrl" alt="photo" />
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TakeREST/Views/Photos/Edit.cshtml
@model TakeREST.Models.Photo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        <div class="container">
            <div class="col-sm-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.AblumID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AblumID, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AblumID, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ThumbnailUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ThumbnailUrl, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ThumbnailUrl, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <img src="@Model.ThumbnailUrl" alt="photo" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TakeREST/Views/Photos/Index.cshtml
@model IEnumerable<TakeREST.Models.Photo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AblumID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThumbnailUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AblumID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThumbnailUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

TakeREST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Take REST", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Photos", "Index", "Photos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Satish Yadav</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>